[package]
name = "rustauc"
version = "0.1.0"
authors = ["Ng Guoyou <ng.guoyou@gmail.com>"]

[dependencies]
iron = '*'
rustc-serialize ="*"
router= "*"
diesel = "0.5.0"
dotenv = "0.8.0"
dotenv_macros = "0.8.0"

[dependencies.diesel_codegen]
git = "https://github.com/sgrif/diesel/"
